name: commune-cache
services:
  commune-cache:
    build:
      context: ../../
      dockerfile: tooling/dockerfile/commune-cache.Dockerfile
    # command: turbo start -F commune-cache
    command: node ./apps/commune-cache/dist/index.js
    ports:
      - "3000:3000"