deployment:
  image:
    repository: ghcr.io/renlabs-dev/commune-governance

  env:
    JWT_SECRET:
      valueFrom:
        secretKeyRef: 
          name: '{{ .Values.environmentName }}-web-apps-secret'
          key: jwt_secret
    POSTGRES_URL:
      valueFrom:
        secretKeyRef: 
          name: '{{ .Values.environmentName }}-web-apps-secret'
          key: community_validator_db_url