deployment:
  image:
    repository: ghcr.io/commune-ai/commune-governance

  env:
    JWT_SECRET:
      valueFrom:
        secretKeyRef: 
          name: 'commune-{{ .Values.environmentName }}-web-apps-secret'
          key: jwt_secret
    POSTGRES_URL:
      valueFrom:
        secretKeyRef: 
          name: 'commune-{{ .Values.environmentName }}-web-apps-secret'
          key: community_validator_db_url